name: Deploy Node.js app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: .ansible/main.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{vars.DOMAIN}} ansible_ssh_port=2222 address=localhost
          options: |
            -e GITHUB_REPO=${{github.repository}}
            -e NODE_ENV=${{vars.NODE_ENV}}
            -e APP_PORT=${{vars.APP_PORT}}
            -e APP_PATH=${{vars.APP_PATH}}
